In [9]:
import numpy as np
from sklearn import preprocessing

data = np.array([[3,5],[7,4],[2,4]])
print(data)

#Way : 1
#mean = average
mean_val = data.mean(axis=0)
print(mean_val)

#Standard Deviation
std = data.std(axis=0)
print(std)

#Mean Removal : it means mean=0, std=1
final_val = data-mean_val
print(final_val)
# print(final_val.mean(axis = 0))
# print(final_val.std(axis = 0))

#Way:2
#scale()
final = preprocessing.scale(data)
print(final)
print(final.mean(axis = 0))
print(final.std(axis = 0))


[[3 5]
 [7 4]
 [2 4]]
[4.         4.33333333]
[2.1602469  0.47140452]
[[-1.          0.66666667]
 [ 3.         -0.33333333]
 [-2.         -0.33333333]]
[[-0.46291005  1.41421356]
 [ 1.38873015 -0.70710678]
 [-0.9258201  -0.70710678]]
[0.00000000e+00 5.92118946e-16]
[1. 1.]
